### ISSUE TITLE
Some recommendations

### ISSUE THREAD

**Issue by ghost** [kompiuter/gofollow#1]
Καλησπέρα Κυριάκο, συγχαρητήρια για το πακετάκι, πρώτη φορά βλέπω άλλον έλληνα gopher! (θα συνεχίσω στα "αγγλικά" τώρα)

---

Hello Kuriakos, greetings from Greece!

You did very good  job for a state of a new gopher, keep going!

I suggest to make the README a little bit attractive in order to welcome more users, for example you can add image or a small gif when running the cli, and  add some screenshots from a real twitter account to show the app's results !

> Let me know if you need anything!

Thanks,
Gerasimos Maropoulos

**Comment by kompiuter** [comment]
Hello Gerasimos, I'm actually Cypriot :)

Thank you very much for your recommendation, duly noted!
